version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always
  react:
    container_name: app-dev
    image: app-dev
    build:
      context: tin_react
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    volumes:
      - "mysqldata:/var/lib/mysql"
      - "$PWD/config/sequelize/initdb:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: on-failure

volumes:
  mongodata:
  mysqldata: