#version: "3.8"
#
#services:
#  app:
#    container_name: app-dev
#    image: app-dev
#    build:
#      target: development
#      context: .
#    volumes:
#      - ./src:/app/src
#    ports:
#      - 3000:3000


version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true